### ISSUE TITLE
new style classes aren't handled correctly

### ISSUE THREAD

**Issue by wapiflapi** [bwall/spickle#1]
I'm not sure if this is supposed to work or not, but the following test cases shows `spickle` returning `None` where the original `pickle` returns the correct object. If this is considered a security issue I was expecting a `UnpicklingError` due to a security flag being raised, and not simply `None`.

```python
import pickle
import spickle                                                                                            


def test(testobj):

    print "Testing: %s" % (testobj,)

    ret = pickle.loads(pickle.dumps(testobj))
    print " pickle returned: %s" % (ret,)

    ret = spickle.loads(spickle.dumps(testobj))
    print "spickle returned: %s" % (ret,)

    print


class Macavity(object):
    pass


if __name__ == '__main__':

    test(Macavity())
```

**Comment by bwall** [comment]
Good catch.  As a result of the reduction in functionality noted here, I'm going to convert the test.py to be actual unit tests which include basic functionality testing as well.

Also, good note on throwing an exception, I have it implemented in my local build.

The fix for this issue in particular is requiring some back sliding on the solution itself, so I need to do a good deal of testing locally to make sure it does not open more gaps.

**Comment by bwall** [comment]
I now have implemented a unit test for this, and it does appear to be working now.  I'm nervous about potential attack surface added by allowing the reconstructor call, but base functionality needs to be maintained.

**Comment by wapiflapi** [comment]
You should be worried. I'm pretty sure this allows code execution again, I'll take a look at it when I  have time, probably not before next week.

**Comment by bwall** [comment]
I did try attacking it with an Unpickler class, but it failed due to a lack of a __new__ method.  In testing I've noticed another loss of functionality in this area, so I'll be making updates soon.  Essentially, Exceptions can't be unpickled with the restricted reducer, so I'm exploring options on how to handle cases where base classes are defined in C.
